/* SPDX-License-Identifier: Apache-2.0 */
#include "jokes.h"

// The complete, unabridged list of 193 dad jokes
const char *JOKES[] = {
    "As I get older, I remember all of the people I lost along the way. Maybe a career as a tour guide wasn’t the right choice.",
    "Went to the bar tonight. Good times. Only a 15-minute walk. But the walk home took 45 minutes, the difference was staggering.",
    "I recently took a pole. And found that 100% of the people in the tent were angry when it collapsed.",
    "Son: \"Dad, can you please explain to me what a solar eclipse is?\" Dad: \"No sun.\"",
    "Why did the man fall down the well? He couldn’t see that well.",
    "I once submitted ten puns to a joke competition. I really thought with that many, one was sure to win. Sadly, no pun in ten did.",
    "Where do you take someone who’s been in a peek-a-boo accident? The ICU.",
    "Did you hear about the explosion at the cheese factory? There was nothing left but debris.",
    "How does NASA organize a party? They planet.",
    "Did you hear the joke about paper? Never mind, it’s tear-able.",
    "What’s orange and sounds like a parrot? A carrot.",
    "What did the blanket say when it fell off the bed? Oh, sheet.",
    "What was even more useful than the first telephone? The second telephone.",
    "I'm afraid for the calendar. Its days are numbered.",
    "Went to the doctor with a suspicious-looking mole. He said they all look that way and I should have left him in the garden.",
    "Have you heard of the new sport called quiet tennis? It’s like normal tennis but without the racket.",
    "Why did the god of thunder need to stretch his legs? He was a little Thor.",
    "What’s the least spoken language? Sign language.",
    "What building in your town has the most stories? The public library.",
    "Claustrophobia is the fear of closed spaces. For example: I'm going to the beer store and I'm scared it will be closed.",
    "If April showers bring May flowers, what do May flowers bring? Pilgrims.",
    "What has five toes but isn’t your foot? My foot.",
    "What looks like half a tree? The other half.",
    "Two guys walked into a bar... the third one ducked.",
    "Why do dads take an extra pair of socks when they play golf? In case they get a hole in one.",
    "What do you call a Frenchman who has been attacked by a cat? Claude.",
    "My 6-year-old daughter has lined up all of her dolls towards the outdoor grill. Looks like she's preparing some kind of barbie queue.",
    "How can you tell the difference between a crocodile and an alligator? Easy, one will see you later, the other will see you in a while.",
    "Someone told me that it’s impossible to make a pun about vegetables. I said that’s not nececelery true.",
    "My friend Jack claims he can communicate with vegetables. Jack and the beans talk!",
    "Where do fruits go on vacation? Pear-is!",
    "What did Baby Corn say to Mama Corn? Where's Pop Corn?",
    "What do you call cheese that isn't yours? Nacho cheese.",
    "What do you call a fake noodle? An impasta.",
    "I tried all morning to cook up an egg-related pun, but I couldn’t crack it.",
    "How do you make an apple turnover? Push it downhill.",
    "What’s brown and sticky? A stick.",
    "I used to play piano by ear. Now I use my hands.",
    "Why did the kid bring a ladder to school? Because she wanted to go to high school.",
    "I asked the librarian if she knew of any authors who wrote dinosaur novels. She said, \"Yes, try Sarah Topps.\"",
    "What did the ocean say to the beach? Nothing, it just waved.",
    "What did the janitor say when he jumped out of the closet? Supplies!",
    "Why can't a nose be 12 inches long? Because then it would be a foot.",
    "I was addicted to the Hokey Pokey.... but I turned myself around.",
    "Why couldn’t the pony sing a lullaby? Because she was a little horse.",
    "What do you say when a chicken is looking at salad? Chicken sees a salad.",
    "What do you call a dog magician? A labracadabrador.",
    "Where would you find an elephant? The same place you lost her.",
    "What’s a dog’s favorite super hero? Labra-Thor.",
    "What do you call a rabbit with fleas? Bugs Bunny!",
    "A man arrives at a costume party with a girl on his back. \"I am a turtle,\" he says. \"Who's on your back?\" \"That's Michelle.\"",
    "Why aren’t dogs allowed in bars? Because they can’t control their licker.",
    "What do you call a deer with no eyes? No eye deer.",
    "Why does a pitcher raise one leg when he throws the ball? If he raises them both, he’d fall down.",
    "Where does a majority of a hockey player’s salary come from? The tooth fairy.",
    "I kept wondering why the baseball was getting bigger. Then it hit me.",
    "Why did the football coach go to the bank? To get his quarter back.",
    "What does a sprinter eat before a race? Nothing, they fast.",
    "Why don't football players were glasses? It's a contact sport.",
    "Why couldn't the baby score in basketball? He was always dribbling.",
    "What's the best animal in soccer? A score-pion.",
    "What happens if no one turns up to your birthday party? You get to have you cake and eat it, too.",
    "Why didn't the teddy bear eat any of its birthday cake? Because it was already stuffed!",
    "Why don't kids remember their past birthday parties? They're too focused on the present!",
    "What type of party do you throw for a dog’s birthday? A ball.",
    "What are you if you go to a ghost birthday party? The life of the party!",
    "Do you know why I get heartburn when I eat birthday cake? I always forget to blow out the candles!",
    "Why do people put birthday candles on top of a birthday cake? Because you can't put them on the bottom, can you?!",
    "What kind of candle burns longer than others? None, silly — they all burn shorter.",
    "Why do candles love birthdays? They like to get lit.",
    "I went to a really emotional wedding last week, even the cake was in tiers.",
    "My antenna married my neighbor’s antenna. The wedding was not so good as this one, but the reception was fantastic!",
    "What do you call a melon that’s not allowed to get married? Can’t elope.",
    "Did you hear about the two spiders who just got engaged? I hear they met on the web.",
    "Did you hear about the two florists who got married? It was an arranged marriage.",
    "Two cannonballs got married this morning. I hear they’re already expecting BBs.",
    "I just saw two nuclear technicians getting married. The bride was radiant, and the groom was glowing.",
    "Dad: Well, you know what they say, the memory is the second thing to go. Son: What's the first? Dad: I forget.",
    "Stop thinking of them as \"hot flashes.\" Think of them as your inner child playing with matches.",
    "I told my doctor I could only hear buzzing. He said don’t worry, it’s just a bug going around.",
    "How is the moon like dentures? Both come out at night.",
    "What do you call someone who enjoys Mondays? Retired.",
    "If you lose something in a senior care home, don't stop looking until you've searched every nook and granny.",
    "An old woman is sitting at a bar when an older gentleman sits down beside her. \"So,\" he says, \"Do I come here often?\"",
    "What is a prize old people can win for aging? Atrophy.",
    "Now that I’ve gotten older, everything’s finally starting to click for me. My knees, my back, my neck…",
    "Birthdays are good for you. The more you have, the longer you live.",
    "My wife found a spider in our house and told me to take it out, so I did. We had a few drinks, pretty nice guy.",
    "My wife screamed, \"You haven’t heard a word I’ve said, have you?!\" What a weird place to start a conversation.",
    "My wife is mad I keep introducing her as my \"ex-girlfriend\". So I went with \"ex-fiancé\" instead.",
    "Wife: \"Our new neighbor always kisses his wife when he leaves for work. Why don't you do that?\" Husband: \"How can I? I don't even know her.\"",
    "Why did Comic Sans divorce Times New Roman? He just wasn’t her type.",
    "I recently visited the \"World’s Tiniest Wind Turbine\" exhibit. Honestly, not a big fan.",
    "How do you follow Will Smith in the snow? You follow the fresh prints.",
    "How does the moon cut his hair? Eclipse it.",
    "\"Dad, did you get a haircut?\" \"No, I got them all cut!\"",
    "Why did the construction workers always bring a pencil to lunch? They wanted to draw their own conclusions!",
    "Why did the sandwich get a promotion? Because he was the best thing since sliced bread.",
    "Why did the employee get fired from the calendar factory? They took a day off.",
    "I used to work for the paper business. But then it folded.",
    "I got fired from my job as a taxi driver. It turns out nobody thought I was fare.",
    "What did the baby computer say to its dad on Father's Day? Happy Father's Day, Data!",
    "Why don’t they have Father’s Day sales? Because fathers are priceless.",
    "Why did the kids give their dad a blanket for Father’s Day? Because they thought he was the coolest dad.",
    "\"Today my son asked me, 'Can I have a bookmark'? I burst into tears — he’s 12 years old and still doesn’t know my name!\"",
    "What did the buffalo say to his son when he dropped him off at school? \"Bison!\"",
    "When does a joke become a dad joke? When it becomes apparent.",
    "What has a spine but no bones? A book.",
    "What would happen if you threw all the books in the ocean? It would cause a title wave.",
    "Did you hear that I’m reading a book about anti-gravity? It’s impossible to put down.",
    "What’s the best kind of music to listen to when fishing? Something catchy.",
    "What kind of music do chiropractors like? Hip pop.",
    "What kind of music does a boulder like? Rock ‘n’ roll.",
    "Singing in the shower is fun until you get soap in your mouth. Then it’s a soap opera.",
    "Why did the man put his money in the freezer? He wanted cold, hard cash.",
    "Where does 007 invest his money? In the bond market.",
    "What did the comedian say when he walked into the bank? This is a standup.",
    "What do you call a Ford Fiesta that ran out of gas? A Ford Siesta.",
    "I couldn’t figure out how to fasten my seatbelt. Then it clicked.",
    "What has 10 letters and starts with G-A-S? Automobile.",
    "Don’t get mad at lazy people. They didn’t do anything.",
    "Interviewer: \"Describe yourself in three words.\" Interviewee: \"Lazy.\"",
    "Want to hear a joke about procrastination? I’ll tell you later.",
    "What do you call a snowman in July? A puddle.",
    "What do you call a Golden Retriever at the beach? A hot dog.",
    "Why don’t fish go on summer vacation? Because they’re always in schools.",
    "We're not socks. But I think we'd make a great pair.",
    "Do you like vegetables? Because I love you from my head tomatoes.",
    "Never laugh at your significant other's choices — because you happen to be one of them.",
    "I burnt my Hawaiian pizza last night. I guess I should have put it on aloha setting.",
    "Don’t trust Adams. They make up everything.",
    "What did the zero say to the eight? That belt looks good on you.",
    "How much does a chimney cost? Nothing, it’s on the house.",
    "Can a frog jump higher than a house? Of course, a house can't jump.",
    "If your house is cold, just stand in the corner. It’s always 90 degrees there.",
    "I told my wife she should embrace her mistakes. She gave me a hug.",
    "I went to buy some camouflage pants, but I couldn't find any.",
    "I was going to tell you a joke about time travel, but you didn't like it.",
    "What was the spider doing on the computer? He was making a web-site.",
    "What did the computer have during his break time? He had a byte!",
    "What shoes do computers love the most? Re-boots.",
    "Why did the computer go to the dentist? To get his Bluetooth checked.",
    "Why do seagulls fly over the sea? If they flew over the bay, they would be bagels.",
    "Why can't a leopard hide? He's always spotted.",
    "What's the best thing about Switzerland? I don't know, but the flag is a big plus.",
    "Why did the orange lose the race? It ran out of juice.",
    "What’s red and bad for your teeth? A brick.",
    "Why are pirates called pirates? They just ARRRR!",
    "How many tickles does it take to make an octopus laugh? Ten-tickles.",
    "Why shouldn’t you tell secrets in a cornfield? Too many ears.",
    "Why did the bicycle fall over? Because it was two tired.",
    "I’m really not into spring cleaning. Come to think of it, I’m not into summer, fall, or winter cleaning either.",
    "I think I want a job cleaning mirrors. It’s just something I could really see myself doing.",
    "When you clean a vacuum cleaner, you become a vacuum cleaner.",
    "My wife and I were having an argument about whose turn it was to do the laundry. In the end, I threw in the towel.",
    "My son has his BA and his MA, but his PA still supports him.",
    "My daughter’s fourth birthday was today. When she came to see me, I didn’t recognize her at first. I had never seen her be four.",
    "I spent a lot of time, money, and effort childproofing my house, but the kids still get in.",
    "Why did the scarecrow join LinkedIn? Because he wanted to become outstanding in his field!",
    "What did the dad say when he couldn't log into his social media account? \"Looks like I'll have to face(book) the music!\"",
    "Why did the dad take a ladder to his Instagram profile? Because he heard it had a lot of posts!",
    "What do you call someone who gets easily annoyed in the comments section? An insta-grump.",
    "I'm reading a book about mazes. I got lost in it!",
    "I'm reading a book about submarines. It's super deep!",
    "I'm reading a book about glue. I can't seem to put it down!",
    "I'm reading a book on clocks. It's about time!",
    "Let’s make a reservation at the library before they’re booked!",
    "What's a librarian's favorite type of music? Shhh-mooth jazz!",
    "Why did the coffee call the cops? It got mugged!",
    "What type of coffee does a vampire drink? Decoffin-ated!",
    "How did the hipster burn his tongue? He drank his tea before it was cool!",
    "How does a coffee bean hit on someone? \"Hey brew-tiful!\"",
    "Why is coffee so good at solving mysteries? Because it always has a latte clues!",
    "What do you call a nervous cup of tea? Anxi-tea!",
    "What's coffee’s favorite type of music? R&Brew!",
    "What do you call a sad cup of tea? Steeped in sorrow!",
    "Why did the tea leaf avoid the hot water? It said, \"I'm not ready to steep into that yet!\"",
    "Why don't oysters go on vacation? Because they're shellfish!",
    "Why do cows love vacation? Because they can moo-ve freely!",
    "Why did the math book go to the beach? To work on its tan!",
    "What did the beach say when the tide came in? Long time, no sea!",
    "Why did the computer go to the beach? To surf the net!",
    "Why don't skeletons get out of town during the Halloween season? They don't have the guts!",
    "Why was the math book upset? It had too many problems.",
    "How do you put together a space party? You planet.",
    "What do you call fake spaghetti? An impasta",
    "I wish I could tell you a joke about an elevator, but it's an uplifting experience.",
    "Why don't airplanes ever get lost? Because they always wing it!",
    "Why did the ghosts go to the party? It was all for the boos.",
    "I used to be a baker, but I couldn't make enough dough.",
    "I used to hate facial hair... but then it grew on me.",
    "Why did the bicycle go to bed so early? It was two-tired!",
    "Why are scientists so skeptical of atoms? Because they make up everything!"
};

// This macro calculates the exact number of elements in the JOKES array at compile time!
const uint16_t NUM_JOKES = ARRAY_LENGTH(JOKES);
